# Generated by Django 6.0.3 on 2026-04-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Idea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Título")),
                ("description", models.TextField(verbose_name="Descrição")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Nova"),
                            ("progress", "Em Progresso"),
                            ("done", "Concluída"),
                            ("archived", "Arquivada"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criada em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizada em"),
                ),
            ],
            options={
                "verbose_name": "Ideia",
                "verbose_name_plural": "Ideias",
                "ordering": ["-created_at"],
            },
        ),
    ]
